name: Terraform Destroy

on:
    workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
  AWS_REGION: 'us-east-1'
  EKS_CLUSTER: 'contour-eks'

jobs:
    terraform_destroy:
        runs-on: ubuntu-latest
        defaults:
            run:
              shell: bash
              working-directory: ./terraform

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Configure AWS credentials
              run: |
                aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws configure set region ${{ env.AWS_REGION }}

            - name: Update kubeconfig
              id: kubeconfig
              run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{env.EKS_CLUSTER}}
      
            - name: Verify kubernetes connection
              run: |
                kubectl get nodes
                kubectl cluster-info
      
            - name: Install Contour Ingress Controller
              if: steps.kubeconfig.outcome == 'success'
              run: |
                kubectl delete -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.12.0-beta.0/deploy/static/provider/aws/deploy.yaml
  
            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v2
            #   with:
                #   terraform_version: 1.0.0

            - name: Terraform Init
              id: init
              run: terraform init -backend-config="bucket=${{ env.BUCKET_TF_STATE }}"

            - name: Terraform Destroy
              run: terraform destroy -auto-approve
